### PR TITLE
Add necessary <script> for Ionic in <head>

### PR DESCRIPTION
**Pull request by suyanzhe**
This script will be a 404 during development, but it is required for Ionic app to work. See http://stackoverflow.com/questions/25961013/how-to-convert-an-existing-angularjs-web-app-to-a-cordova-app

### CODE REVIEW

**Comment by jacoblxliu** [comment]
Maybe we can merge it later? Because it is 404 anyway and we only need it after the ionic framework is ready to be incorporated?

**Comment by jacoblxliu** [comment]
What do others think?

**Comment by suyanzhe** [comment]
I just pushed a new commit to my repo. This pull request now also resolves #31 and #32, at least partly.

**Comment by suyanzhe** [comment]
I made a new commit. Now right after login the system should go to frame.html instead of dashboard.html.

**Comment by jacoblxliu** [comment]
I checked your code on my browser. The frame.html view is empty. And the side navigation height problem is not fixed. profile.html, event.html, team.html all of them do not have any formatting anymore.

How did this happen?

**Comment by jacoblxliu** [comment]
You can refactor existing code or beautify, improve existing view. But the view is disrupt now. I cannot merge this PR until later.

**Comment by suyanzhe** [comment]
Actually the reason that the view is disrupted in Chrome is explained in http://stackoverflow.com/questions/8449716/cross-origin-requests-are-only-supported-for-http-but-its-not-cross-domain. You could try to put it on an AWS instance to see if the problem is resolved. The new commit d714503 solves the problem mentioned in the lab.

**Comment by jacoblxliu** [comment]
1. It does work on Firefox. But it must work on Chrome as well. It is a issue that it does not work on windows Chrome. Maybe you can fix that.
2. To achieve your refactoring, you modified backend behavior. That part must be approved by backend guys.
3. Click on the update profile button does not direct to profile editing page.
4. The view now has some alignment problem after you fix the side navigation bar height problem.
   
   As you can see on that picture.

**Comment by jacoblxliu** [comment]
Of course we appreciate your code and we will not make your work in vein. But it needs to work first :)

And we need backend guys to review your modification on backend @JakePickle , maybe @suyanzhe  you can explain what part in backend you modified.

For now I will keep working on other views based on the original master, instead of this PR, to make sure the code will not be broken.

**Comment by suyanzhe** [comment]
Maybe I need to branch out the refactorings, concerning fix to the layout problem first. This pull request is ways too large.

**Comment by suyanzhe** [comment]
Separate the refactorings, when ready, to a new PR when things are ready.

**Comment by jacoblxliu** [comment]
That is a perfect idea! Branching is always more flexible than directly pushing all these change to master~

If a pull request is just to add new code, then it can be large. But if is to change existing code, then it better be modularized.

**Comment by jacoblxliu** [comment]
And after I finish coding other views, you can refactor together. That can save time.

**Comment by suyanzhe** [comment]
Those reverted changes are kept in a separate branch called refactoring.

**Comment by suyanzhe** [comment]
Please review the new, not so radical commit ba39a99, and merge this if it is okay.

**Comment by jacoblxliu** [comment]
asdaddsa
There are still 2 scroll bar?
Does this PR points to your newest commit or your original commit?

**Comment by suyanzhe** [comment]
This points to my newest commit. I set a minimum height on the left nav.

**Comment by suyanzhe** [comment]
If possible, could you make the window larger? On larger windows there should not be 2 scrollbars anymore.

**Comment by jacoblxliu** [comment]
I am just about to merge my new explore view. There will be some minor conflicts for your commit. Please address them altogether (The two scroll bar and some small conflicts of my newly merged commit), Then create PR, then I will merge.

**Comment by jacoblxliu** [comment]
Oh, I thought the two scroll bar is fixed for all screen resolution.
Ok, I will address the conflicts and merge.
Or maybe if you are not busy you can resolve the conflicts?

**Comment by jacoblxliu** [comment]
Ok, I fix the conflicts.

**Comment by suyanzhe** [comment]
We are both trying to resolve the conflicts and now it is a different file that conflicts!

**Pull request merged**
