### PR TITLE
Use versions of libraries specified by Peter

### PR DESCRIPTION
**Pull request by suyanzhe**
The versions of libraries are already specified by Peter and provided in the original project structure. Especially, Firebase 2.2.4 is not okay for the project, version 3.x required. In project specification `Firebase (v3.0.3) - It is NOT allowed to use the legacy Firebase (i.e. 2.x) API`

### CODE REVIEW

**Comment by suyanzhe** [comment]
I am fixing the typos in the comment of #57 here.

**Comment by suyanzhe** [comment]
Please redo #54. The change to firebase version is compulsory.

**Comment by Patric-Lee** [comment]
As who did #54, I am sure I am using Firebase version 3.x.x. And the code is based on the tutorial on AngularFire website. I wonder the reason why you think legacy APIs are used. Have I mistakenly using some of them?

**Comment by Patric-Lee** [comment]
Okay. I am sorry about my mistake. The change would be applied soon.

**Comment by Patric-Lee** [comment]
I have fixed the version issue. In the forthcoming pull request it would be applied.

**Comment by suyanzhe** [comment]
Thank you very much. I am still waiting for the "forthcoming pull request"

**Pull request merged**
